wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710269070.0
    t:
      1:
      - 1
      - 41
      - 55
      - 100
      2:
      - 1
      - 41
      - 55
      - 100
      3:
      - 2
      - 23
      - 37
      4: 3.10.12
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
embed_size:
  desc: null
  value: 512
hidden_size:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 0.007793450338735142
num_epochs:
  desc: null
  value: 1
num_layers:
  desc: null
  value: 1
patience:
  desc: null
  value: 4
